//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BarterMarket.Logic.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class CashOperation
    {
        public int CashOperationID { get; set; }
        public int UserID { get; set; }
        public int CashOperationTypeID { get; set; }
        public int CashAmount { get; set; }
        public Nullable<int> CertificateID { get; set; }
        public Nullable<int> CertificateCount { get; set; }
        public System.DateTime OperationDate { get; set; }
    
        public virtual Certificate Certificate { get; set; }
        public virtual User User { get; set; }
        public virtual CashOperationType CashOperationType { get; set; }
    }
}
