//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BarterMarket.Logic.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class CashOperationType
    {
        public CashOperationType()
        {
            this.CashOperations = new HashSet<CashOperation>();
        }
    
        public int CashOperationTypeID { get; set; }
        public string CashOperationTypeName { get; set; }
        public bool IsIncrementOperation { get; set; }
    
        public virtual ICollection<CashOperation> CashOperations { get; set; }
    }
}
