//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BarterMarket.Logic.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Certificate
    {
        public Certificate()
        {
            this.CashOperations = new HashSet<CashOperation>();
        }
    
        public int CertificateID { get; set; }
        public int PacketID { get; set; }
        public Nullable<int> CustomerID { get; set; }
        public string CertificateCodeValue { get; set; }
        public System.DateTime CertificateCreateDate { get; set; }
        public Nullable<System.DateTime> CertificateImplementDate { get; set; }
        public bool CertificateIsImplement { get; set; }
    
        public virtual ICollection<CashOperation> CashOperations { get; set; }
        public virtual User User { get; set; }
        public virtual Packet Packet { get; set; }
    }
}
