//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BarterMarket.Logic.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class OfferRequest
    {
        public int OfferRequestID { get; set; }
        public string CompanyName { get; set; }
        public string CompanyAddress { get; set; }
        public string CompanyRegistrationRegion { get; set; }
        public string CompanyRegions { get; set; }
        public string CompanySite { get; set; }
        public string CompanyDetails { get; set; }
        public string UserName { get; set; }
        public string TelephoneNumber { get; set; }
        public string SourceAboutUs { get; set; }
        public string AdvertisingTarget { get; set; }
    }
}
