//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BarterMarket.Logic.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Offer
    {
        public Offer()
        {
            this.Packets = new HashSet<Packet>();
        }
    
        public int OfferID { get; set; }
        public string OfferName { get; set; }
        public int OfferCategoryID { get; set; }
        public int UserID { get; set; }
        public string OfferCompanyAddress { get; set; }
        public string OfferManagerName { get; set; }
        public string OfferManagerPhone { get; set; }
        public string OfferManagerEmail { get; set; }
        public string OfferDetails { get; set; }
        public string OfferInstagramLink { get; set; }
        public string OfferVKLink { get; set; }
        public string OfferOdnoklassnikiLink { get; set; }
        public string OfferFacebookLink { get; set; }
        public string OfferTwitterLink { get; set; }
        public string OfferWhatsappLink { get; set; }
        public string OfferTelegramLink { get; set; }
        public string OfferViberLink { get; set; }
        public byte[] OfferPhoto { get; set; }
        public System.DateTime OfferDate { get; set; }
        public string ImageType { get; set; }
        public int OfferStatusID { get; set; }
    
        public virtual OfferCategory OfferCategory { get; set; }
        public virtual User User { get; set; }
        public virtual OfferStatus OfferStatus { get; set; }
        public virtual ICollection<Packet> Packets { get; set; }
    }
}
