//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BarterMarket.Logic.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Packet
    {
        public Packet()
        {
            this.Certificates = new HashSet<Certificate>();
        }
    
        public int PacketID { get; set; }
        public int OfferID { get; set; }
        public int PacketCost { get; set; }
        public int PacketsCount { get; set; }
        public System.DateTime PacketDate { get; set; }
        public string PacketName { get; set; }
        public int PacketStatusID { get; set; }
    
        public virtual ICollection<Certificate> Certificates { get; set; }
        public virtual Offer Offer { get; set; }
        public virtual PacketStatus PacketStatus { get; set; }
    }
}
