//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BarterMarket.Logic.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class PacketStatus
    {
        public PacketStatus()
        {
            this.Packets = new HashSet<Packet>();
        }
    
        public int PacketStatusID { get; set; }
        public string PacketStatusName { get; set; }
    
        public virtual ICollection<Packet> Packets { get; set; }
    }
}
