//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BarterMarket.Logic.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.Offers = new HashSet<Offer>();
            this.CashOperations = new HashSet<CashOperation>();
            this.Certificates = new HashSet<Certificate>();
        }
    
        public int UserID { get; set; }
        public string UserNick { get; set; }
        public string UserEmail { get; set; }
        public string UserPassword { get; set; }
        public int UserRoleID { get; set; }
        public string UserCompanyName { get; set; }
        public string UserCompanyDetails { get; set; }
        public System.DateTime UserRegisrationDate { get; set; }
        public int UserPiarsCount { get; set; }
        public string UserPhone { get; set; }
        public string Network { get; set; }
        public string Uid { get; set; }
    
        public virtual UserRole UserRole { get; set; }
        public virtual ICollection<Offer> Offers { get; set; }
        public virtual ICollection<CashOperation> CashOperations { get; set; }
        public virtual ICollection<Certificate> Certificates { get; set; }
    }
}
